import type { Metadata } from "next";
import Header from "../components/modules/layouts/header";
import "./globals.css";

export const metadata: Metadata = {
  title: "cfla.tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="ja-jp">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
